module "qumulo_cluster" {
  source             = "./cluster"
  aws_region         = "us-east-1"
  aws_az             = "us-east-1a"
  node_type          = "af"
  cluster_name       = "berat-qumulo"
  instance_type      = "m5.xlarge"
  node_count         = 4
  key_pair_name      = "bulualan2"
  vpc_id             = "vpc-55160233"
  subnet_id          = "subnet-3bd08e5e"
  security_group_ids = []
  cidr_block         = "172.31.0.0/24"
  persistent_ips     = "172.31.0.5-8"
  floating_ips       = "172.31.0.9-20"
  define_dns_records = false
  route53_zone       = ""
  igw_enable         = true
}
